#  Code generated by AI

import re


def main():
    print(convert(input("Hours: ")))


def convert(s):
    pattern = r"(^\d{1,2})(:\d{2})? ([AP]M) to (\d{1,2})(:\d{2})? ([AP]M)$"
    match = re.search(pattern, s)

    if not match:
        raise ValueError

    hour_start = int(match.group(1))
    min_start = match.group(2) or ":00"
    start_period = match.group(3)

    hour_end = int(match.group(4))
    min_end = match.group(5) or ":00"
    end_period = match.group(6)

    def convert_time(hour, minutes, period):
        if hour > 12 or int(minutes[1:]) > 59:
            raise ValueError
        if period == "AM" and hour == 12:
            hour = 0
        elif period == "PM" and hour != 12:
            hour += 12
        return f"{hour:02}{minutes}"

    return f"{convert_time(hour_start, min_start, start_period)} to {convert_time(hour_end, min_end, end_period)}"


if __name__ == "__main__":
    main()
